log_path: /root/code/trade/log
# log_name: xiaomi
longport:
  candlestick_amount: 100
  app_key: fddd1f64ad477d0aea79928c749cc581
  app_secret: d7873d6e17dbff6c0f1bb6ccf3f5a638f044ee9b6ba7f87e92399c8e8164357e
  access_token: m_eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsb25nYnJpZGdlIiwic3ViIjoiYWNjZXNzX3Rva2VuIiwiZXhwIjoxNzc0MTczNjcxLCJpYXQiOjE3NjYzOTc2NzIsImFrIjoiZmRkZDFmNjRhZDQ3N2QwYWVhNzk5MjhjNzQ5Y2M1ODEiLCJhYWlkIjoyMDMzOTI4NywiYWMiOiJsYiIsIm1pZCI6MTM3NjkyNjcsInNpZCI6ImVlZEx4b08zMnlsS0g5T1N6NVZWNEE9PSIsImJsIjozLCJ1bCI6MCwiaWsiOiJsYl8yMDMzOTI4NyJ9.ScWvXHOhNYWhadf925w5XgOLU_2-P2GuuPbu5vtfFkWdWdSgBGPmg0Bvi10x-dE-xRIztA5pfx0-BrG1uWzmDydoW6C5kmGE3hMvEdqvOL5qW52aF7zsoH8xH0oEGE8g4oMKj9Tw8LAmfdBhm0OQThOVRArMO5Izu9NJbbHN-VnFhTcEC4k9tMLj3592hFtigH1RD_dEjZaFSgGptgkBQSdklAXChSf-8R-QKLQBZ_-QNJGBbjfm90yQ6U_wxWLS2pWG7e0B7QLqLQIZmXusMas-s2XjO71sHXOIiyy3tFPplpQz7hoUYCIsLdi0BILdJj3rRsnS1pA9Dx9gkGlFy0el4nA1IMM0b2Z-5kwE0J0QJs8IFTgEUe-PFt5U7-rJ3wX2jwCJJS04mgnx3f1RKEV7-6zWWrQSl-oqB5LClms-Kq5Y15m4SU-XT4NDnpeW7D2oXTFWJpcPuDa1-o7jYGj6I0Kc1Ces-2YCdNn8hVE9VC-vXHqOZ_y386Tu076Plw7CX50abInE-RiWBvvoV21PRYxjDSihluVIsSLzAwUkmywjFDUPQSsYS2zqjujTv63O27NMy_D5yD5q8A8z5vWsv8NvP6KbJmsJN2HZ9Kqnjac-T6NBJCh3OGBtL7kk_F8b4JhzJ6aTSgJBcyBvYnMiCDM0APbIX2_O_SJHASI

feishu:
  app_id: cli_a8245771a9fa101c
  app_secret: 4QmHdH2XrhBnSmd9tN73LPvnPwiiWxPh
  open_id: ou_d3db55004e78fd1d378d239fae7c43bf

    #risk_management: 
    #  name: NetTrader
    #  first_amount: 1200
    #  amount: 600
    #  delta_price: 0.5

#stock_id: "09660.HK"
#stock_id: "MSTX.US"
#stock_id: ['MSTX.US', 'MSTZ.US','01810.HK','00558.HK']

    #log_name: xiaomi
    #stock_id: ["01810.HK"]
    #strategy: 
    #  name: NetTrader
    #  first_amount: 1200
    #  amount: 600
    #  delta_price: 0.5

#log_name: MSTX
#stock_id: ["MSTX.US"]
#strategy: 
#  name: NetTrader
#  first_amount: 60
#  amount: 20
#  delta_price: 0.5

# strategy: 
#   name: MACD
#   period_1: 30
#   period_2: 50
#   amount: 600

log_name: CallMacd
strategy: 
   name: CallMacd 
   period_1: 12
   period_2: 26
   period_3: 9
   delta: 0.03
