log_path: /root/code/trade/log
# log_name: xiaomi
longport:
  app_key: fddd1f64ad477d0aea79928c749cc581
  app_secret: d7873d6e17dbff6c0f1bb6ccf3f5a638f044ee9b6ba7f87e92399c8e8164357e
  access_token: m_eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsb25nYnJpZGdlIiwic3ViIjoiYWNjZXNzX3Rva2VuIiwiZXhwIjoxNzY1ODg2Njg1LCJpYXQiOjE3NTgxMTA2ODUsImFrIjoiZmRkZDFmNjRhZDQ3N2QwYWVhNzk5MjhjNzQ5Y2M1ODEiLCJhYWlkIjoyMDUxMzYxNywiYWMiOiJsYl9wYXBlcnRyYWRpbmciLCJtaWQiOjEzNzY5MjY3LCJzaWQiOiI5ZmVHQkZBRlFjSUtFend3b0xIMG5RPT0iLCJibCI6MywidWwiOjAsImlrIjoibGJfcGFwZXJ0cmFkaW5nXzIwNTEzNjE3In0.b1R7ONeda5KkExwJPq--S4YVR_TwaT55iKK6msagEugChR6y5CErOzJqQa-gZ9wT46p_GgTdqASWaNya2MGPIu71dlxoecy4jDgrvms1nAJgJhxgMRkiPx0AaqQ1pJHr8Kz-hfj6pudUe5mkS4uQT3S_DgksRAES4WQuthxZEpfrbKH_ldiDTDUr_8yC8nqfBJjs8sjLGo_fInVA8Vy5uGLpEzWJkf19xxiv-_viM691ia8_BygSQBaPUc-unb-3vKgex7JLeba0gfGvLfoqcy2-fLtmdxGrskd6HW9dvYv05yVPBNElJ7V2vP2XLzxioLLBdjSO3Y144cLm4iM5G5au2vgo8T7cvGEKMgRci9gulXMwZW_oXJK234FW0gn2fjpmsGZj_rHoCpKm5wMV3w5HsH4oo1VPXc0xFHva0Tojd1OZ_6achIX4RlOwOSXzi2C6ilJVxQpULqoF6k1A9AbvGovSw8NyBLq5BS0JLFteNq10UaPXhiQxrwjZvIbniJGLXnUnIfJ4PE1kXMNLXjPa0v4qra-7ftQm_P20VDBD61YNMYdwjmJrFcabyBQiZMEwlZ-trU1hGvPXrpXe-OnBH60rmKLxyDCVnBAtaVnY00dNODBcJDFZcZuFTXH2khCAUrP4ilzGUMGBKBleUyJ_nUuuUUV8mGf187LCAYQ
  candlestick_amount: 100

feishu:
  app_id: cli_a8245771a9fa101c
  app_secret: 4QmHdH2XrhBnSmd9tN73LPvnPwiiWxPh
  open_id: ou_d3db55004e78fd1d378d239fae7c43bf

risk_management: 
  name: NetTrader
  first_amount: 1200
  amount: 600
  delta_price: 0.5

#stock_id: "09660.HK"
#stock_id: "MSTX.US"
#stock_id: ['MSTX.US', 'MSTZ.US','01810.HK','00558.HK']

#log_name: xiaomi
#stock_id: ["01810.HK"]
#strategy: 
#  name: NetTrader
#  first_amount: 1200
#  amount: 600
#  delta_price: 0.5

#log_name: MSTX
#stock_id: ["MSTX.US"]
#strategy: 
#  name: NetTrader
#  first_amount: 60
#  amount: 20
#  delta_price: 0.5

# strategy: 
#   name: MACD
#   period_1: 30
#   period_2: 50
#   amount: 600

log_name: CallMacd
strategy: 
  name: CallMacd
  period_1: 12
  period_2: 26
  period_3: 9
